### ISSUE TITLE
tacotron code is not working

### ISSUE THREAD

**Issue by weegwangjin** [keithito/tacotron#139]
In train.py
` audio.save_wav(waveform, os.path.join(log_dir, 'step-%d-audio.wav' % step))`

This code load audio.save_wav function 

In audio.py

`def save_wav(wav, path):
  wav *= 32767 / max(0.01, np.max(np.abs(wav)))
  librosa.output.write_wav(path, wav.astype(np.int16), hparams.sample_rate)`
and then this code load librosa.output.write_wav function.
and that convey wav.astype(np.int16) parameter 

however, in librosa.output.wirte_wav 

This function checks whether it is a float. This is logically strange.

why does it convert wav type to np.int16???
and this code is right??

**Comment by keithito** [comment]
This is to output 16-bit samples because some players have trouble with floating-point samples. It looks like librosa added the code to check that it's a float in 0.6.0 (not sure why -- it looks like it's just a wrapper on scipy.io.wavfile.write which seems to handle int16 samples fine). Please make sure you're using the librosa version in requirements.txt (0.5.1).

**Comment by weegwangjin** [comment]
Thank you !!! @keithito
