### ISSUE TITLE
save audio error when run train

### ISSUE THREAD

**Issue by superhg2012** [keithito/tacotron#148]
when I run train after 1000 steps, encountered an exception while saving auido.

Traceback (most recent call last):
  File "train.py", line 115, in train
    audio.save_wav(waveform, os.path.join(log_dir, 'step-%d-audio.wav' % step))
  File "/tts/tacotron/util/audio.py", line 16, in save_wav
    librosa.output.write_wav(path, wav.astype(np.int16), hparams.sample_rate)
  File "/usr/local/lib/python3.5/dist-packages/librosa/output.py", line 223, in write_wav
    util.valid_audio(y, mono=False)
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/utils.py", line 159, in valid_audio
    raise ParameterError('data must be floating-point')
librosa.util.exceptions.ParameterError: data must be floating-point

I find the save_wav function below:
def save_wav(wav, path):
  wav *= 32767 / max(0.01, np.max(np.abs(wav)))
  librosa.output.write_wav(path, wav.astype(np.int16), hparams.sample_rate)

wav.astype(np.int16) should be np.floatxx?

**Comment by TheNarrator** [comment]
Did you make sure to install the correct version `librosa==0.5.1`?

**Comment by mingfengwuye** [comment]
This error will happen when you install default librosa. The version is 0.6

**Comment by superhg2012** [comment]
@mingfengwuye @TheNarrator thanks a lot, it works now!

**Comment by ryancwalsh** [comment]
@superhg2012 @mingfengwuye If downgrading to librosa 0.5.1 is necessary, how can I do it?

I ran `pip uninstall librosa`, which returned `Successfully uninstalled librosa-0.6.1`.

But `pip install librosa 0.5.1` results in:

```
Collecting librosa
Collecting 0.5.1
  Could not find a version that satisfies the requirement 0.5.1 (from versions: )
No matching distribution found for 0.5.1
```

And `pip install librosa-0.5.1` doesn't find a version to install either.

Thanks for any advice.

P.S. I found this page because when I run `python demo_server.py --checkpoint pretrained_model/tacotron-20170720/model.ckpt` and then type some text to synthesize in my browser at http://localhost:9000, I get the error `librosa.util.exceptions.ParameterError: data must be floating-point`, which led me to this Github issue.

**Comment by ryancwalsh** [comment]
Ahh I was supposed to type `pip install librosa==0.5.1`. That worked.

And the demo in the browser now works! It spoke "That was pretty cool." :-)

I'm excited. Next step: trying to change the voice based on my own audio clips. I have no idea how to do that yet.
