### ISSUE TITLE
How can the output dim of ConcatOutputAndAttentionWrapper be 512 on Tacotron2 branch

### ISSUE THREAD

**Issue by begeekmyfriend** [keithito/tacotron#168]
In [tacotron.py](https://github.com/keithito/tacotron/blob/tacotron2-work-in-progress/models/tacotron.py#L64) we can see the `attention_depth` is set as 128 and then it is wrapped into `ConcatOutputAndAttentionWrapper` in which the attention RNN output and the context will be concatenated together. But I guess the concatenated dim should be 256 instead of 512.

**Comment by begeekmyfriend** [comment]
@syang1993 What you are watching is the master branch and what I am saying is the `tacotron2-work-in-progress` branch where the [attention_depth](https://github.com/keithito/tacotron/blob/tacotron2-work-in-progress/hparams.py#L31) is set as 128.

**Comment by syang1993** [comment]
@begeekmyfriend  It's the same in the `tacotron2-work-in-progress` branch, I just set it as an example. For this branch, the dim is also `hp.attention_depth + hp.encoder_depth*2=640` (Since it use BLSTM, so the dim of `cell_output` is 2*'hp.encoder_depth'). 

You can see the implementation of `AttentionWrapper` for details:

[https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py](url)

the `attention_depth` in this repo will only affect the query and key depth of the attention mechanism.

**Comment by begeekmyfriend** [comment]
@syang1993 I just printed the `output_size` of each cell. You are right.
