### ISSUE TITLE
synthesizing unclear audio for the words not seen during training

### ISSUE THREAD

**Issue by sravand93** [keithito/tacotron#271]
Hi 
I have trained the network on arctic data set. After 131k iterations, I am trying to synthesis the audio. For some words(that are general and mostly seen during training) i am getting the audio good, but for the words that are not in training, the output is very bad. Please see the results below
1. Text : "we are waiting for the better results to come and apply them there"
output speech : https://drive.google.com/file/d/10BAw7okHr4UDSKZZbvbD92tgeXRl4nRK/view?usp=sharing

2. Text : "During eval and training audio length is limited to"
output : https://drive.google.com/file/d/10Bqsq7hR21DlL3hgrQdpKNNLprm9Exjv/view?usp=sharing

 Also for some of the output the last term is constantly repeating.

3. Text :" we are waiting for the better results to come and apply them here"
output : https://drive.google.com/file/d/10AudjhmaUxDgCSPlliUFToxpMEiDOFZk/view?usp=sharing

Any suggestions to generalize the model for all the words and for last word repeating? 

Thanks

**Comment by keithito** [comment]
ARCTIC is a fairly small dataset so you may be overfitting. Are you using a single speaker or all of the speakers? If it's the latter, you may want to add speaker embeddings so the model can learn the difference between speakers.

As for the repeat at the end, this is sometimes an issue with Tacotron since it doesn't explicitly learn when to stop. You may have better luck with the Tacotron 2 architecture; there are several implementations on Github:
https://github.com/Rayhane-mamah/Tacotron-2
https://github.com/NVIDIA/tacotron2

**Comment by sravand93** [comment]
@keithito Thank you for the suggestions. I will try with the tacotron 2 architecture implementations

**Comment by ArtemisZGL** [comment]
@sravand93 hello, do you use one speaker in arctic to train?
