### ISSUE TITLE
Pretrained model doesn't work

### ISSUE THREAD

**Issue by nfrik** [keithito/tacotron#28]
First of all thank you for the code and detailed instruction. I followed your instructions and downloaded archive with pretrained model, however there is no model.ckpt file, instead there is only intermediate checkpoint :-(

**Comment by ElevenGameStudios** [comment]
the model is contained in the file model.ckpt.data-00000-of-00001 and its index file. it should work if you use it like described. (python demo_server.py --checkpoint PATH_TO_FILE   while leaving out the ".data-00000-of-00001") i too was confused at first, because it seemed to be a different file extension compared to ".ckpt".

**Comment by nfrik** [comment]
Thank you very much!

**Comment by Luzeru** [comment]
@keithito @ElevenGameStudios
Hello：
There are three files related to the model. 
For example, model.ckpt-8000.data-00000-of-00001,  model.ckpt-8000.index ,  model.ckpt.meta. 
Can you tell me the meaning of every representative of the document？
Thanks very much！
