### ISSUE TITLE
Short explanation for preprocessing setup for linear spectrogram

### ISSUE THREAD

**Issue by gmkim90** [keithito/tacotron#38]
Thanks for sharing your code.
It seems that this code have additional preprocessing step which is not listed in tacotron paper.
And this additional preprocessing make learning more easy task compared to other code without preprocessing.
Could you provide short explanation/comment on few related questions?
And if possible, could you provide reference related to this?

1) What is the role of preemphasis for speech synthesis?

2) What is the advantage when learning on log10(spectrogram)?

3) What is the advantage when data is normalized to lie between 0 and 1?

I appreciate your answer.

**Comment by keithito** [comment]
Sure!

> What is the role of preemphasis for speech synthesis?

Preemphasis increases the magnitude of higher frequencies and decreases the magnitude of lower ones. It's sometimes used in speech recognition because the higher frequencies can provide a better signal for that task. I'm not sure why it would be useful for synthesis, but the Tacotron paper says it helped. It might be interesting to remove it and see what difference it makes.


> What is the advantage when learning on log10(spectrogram)?

We perceive loudness roughly on a log scale. Since we want errors that are equally loud to contribute an equal amount to the loss, it makes sense to use a log representation. The choice of base 10 is arbitrary, but it matches the decibel scale which is used a lot in audio applications.


> What is the advantage when data is normalized to lie between 0 and 1?

The model doesn't have a way to signal the end of output. Instead, it just learns to generate padding frames, and since we're using zero-padding, it's convenient to map 0 to silence so that after the speech ends, the model generates silence. I don't think it matters that the upper limit is 1, though maybe it helps a little to keep the weights reasonable.
