### ISSUE TITLE
hyperparam use cmu_dick

### ISSUE THREAD

**Issue by 493238731** [keithito/tacotron#52]
Thank you for your work.I'll retrain it in other language, it may not use cmu dick?
I want to know  whether the demo sample use cmu dick?
It uses English letter or  cmu dick as inputs?

**Comment by keithito** [comment]
The demo used use_cmudict=true set. This causes it to train on both English letters and phonemes so that you can use either (or a combination of both) as input. However, you can get similar results with use_cmudict=false -- you just won't be able to force particular pronunciations by passing phonemes.

**Comment by 493238731** [comment]
Sorry, I don't describe my question explicit. What I want to ask is  whether it using phones or letter in eval/demo_server stage. After view your code not very detailed, It inputs only letter in eval/demo_server stage, is it right? And your demo sample inputs letter only?

**Comment by 493238731** [comment]
It iｓ embarrassed that you have answered my question on Miscellaneous Notes. Ｉgnore me, you can pretend not seen ^_^

**Comment by 493238731** [comment]
It iｓ embarrassed that you have answered my question on Miscellaneous Notes. Ｉgnore me, you can pretend not seen ^_^
