### ISSUE TITLE
Some problems with non-English dataset

### ISSUE THREAD

**Issue by toannhu** [keithito/tacotron#77]
First of all, I'm really appreciate all of your job here, make this thing become wonderful repo. I'm a student and trying to use this implementation to synthesize Vietnamese for pet project. Because Vietnamese is a tonal language and have accent mark (ex: Xin chào (vietnamese) = Hello) so I have to change something in repo code. 
+ The dataset is about 2 hours and I format this just like LJSpeech
+ In `text/symbols` I changed _character into `_characters = 'AÁÀẠẢÃĂẰẮẶẲẴÂẤẦẬẨẪBCDĐEÉÈẺẼẸÊẾỀỂỄỆFGHIÍÌỊỈĨJKLMNOÓÒỌỎÕƠỚỜỢỠỞÔỐỒỘỖỔPQRSTUÚÙỤỦŨƯỨỪỰỮỬVWXYZaáàạảãăắằặẳẵâấầậẩẫbcdđeéèẻẽẹêếềểễệfghiíìịỉĩjklmnoóòọỏõơớờợỡởôốồộỗổpqrstuúùụủũưứừựữửvwxyz!\'(),-.:;? '` and I also changed `cleaner` in `hparams` to `basic_cleaners`
+ In `audio.py`, I added `librosa.effects.trim` to trim leading and trailing silence sound.
Then I went to training stuff and when I got to step 10000, i want to test if the model could generate some sound for me but the only thing that i received is just one beep sound and it doesn't last even for 1 second :(
I just try to figure out what is happening for the whole 2 days but i still don't know why and how to fix it so I really need some help. I will attach some pictures, sounds and logs file below here. Tks for support.
P/s: Sry for the bad English though.
[source.zip](https://github.com/keithito/tacotron/files/1503921/source.zip)

**Comment by keithito** [comment]
- Try training for longer. 10000 steps is a little bit short for learning a good alignment, and looking at your alignment images, it seems like that may be the case.
- It also appears from the images that it's learning to start attending the beginning of the input at a late decoder timestep. This could be caused by not properly trimming the audio. You may want to verify that librosa is correctly trimming the audio.  `librosa.effects.trim` doesn't always work well with the defaults; you may need to tune some of the optional parameters.
- The synthesis code has a heuristic to trim the audio when it thinks it's over.  If your model is learning to synthesize silence at the start of the output, this may not work properly. Try commenting out this line:
https://github.com/keithito/tacotron/blob/master/synthesizer.py#L37

Hope that helps!

**Comment by toannhu** [comment]
@keithito I think change the parameter `top_db` to higher value in `librosa.effects.trim` will make the difference. I'll try and report the result to you later. Tks for helping me.
Btw, if i change the `batch_size` to smaller value, will the model learn alignment badly? Because my GPU has only 2GB RAM so it can only handle batch_size 16 :(

**Comment by keithito** [comment]
Yes, decreasing batch_size is fine.
